runtime: python39
entrypoint: gunicorn --chdir ./server -b :$PORT main:app
env_variables:
    FLASK_ENV: "production"
    FLASK_TOKEN: %_FLASK_TOKEN%
    SECRET_KEY: %_SECRET_KEY%
    MONGO_DBNAME: "agp_db"
    MONGO_URI: %_MONGO_URI%
handlers:
    - url: /.*
      script: auto
      secure: always